version: '3.1'

services:
  libredte:
    build: ${PWD}/libredte
    #volumes:
    # - ${PWD}/app:/app
  apache:
    build: ${PWD}/apache
  postgres:
    image: postgres:13-alpine
    env_file: db.env

