version: '3.1'

services:
  libredte:
    build: ${PWD}/libredte
    env_file: .env
    #volumes:
    # - ${PWD}/app:/app
  apache:
    build: ${PWD}/apache
    ports:
        - 80:80
  postgres:
    image: postgres:13-alpine
    env_file: .env

